# Builds public/data.json (English + Arabic): 3000 truths + 3000 dares each (20 frames x 150 topics each). Edit lists, then run: python3 generate.py
import json
TF=["Tell me the full story of {t}.","What's your favorite memory of {t}?","How do you honestly feel about {t}?","What is one thing nobody knows about {t}?","If you could relive {t}, what would you do differently?","When was the last time you thought about {t}?","What surprised you most about {t}?","Describe {t} in three honest words, then explain them.","What's the funniest part of {t}?","Who else knows about {t}, and what did they say?","What would your younger self say about {t}?","What's the best thing that came out of {t}?","Rate {t} from 1 to 10 and explain your number.","What part of {t} still makes you smile?","What part of {t} still makes you nervous?","What did you learn from {t}?","If a movie was made about {t}, what would it be called?","What's something you've never told me about {t}?","How has {t} changed you?","What question do you wish I would ask you about {t}?"]
DF=["Send a voice message telling the story of {t}.","Describe {t} using only emojis.","Write a four-line poem about {t}.","Text me a one-sentence review of {t}, like a movie critic.","Send a voice message singing a made-up song about {t}.","Act out {t} in a 20-second voice note.","Write a headline about {t} as if it were breaking news.","Explain {t} to me as if I were five years old.","Send a selfie that matches how you feel about {t}.","Tell me about {t} in exactly ten words.","Give {t} a dramatic movie-trailer voiceover in a voice note.","Write a short thank-you note about {t}.","Come up with a slogan for {t}.","Do a quick impression of yourself talking about {t}.","Share a photo or drawing that reminds you of {t}.","Text me a riddle about {t} and let me guess.","Whisper a secret about {t} in a voice message.","Give {t} a score out of 10 in a voice message and defend it.","Create a hashtag for {t} and use it in a sentence.","Describe {t} in the voice of a nature-documentary narrator."]
TOP={
"romantic":["our first date","the day we met","your first impression of me","the way I make you laugh","our favorite song","the first time you thought of me","your dream date night","the nicest thing I ever did for you","our first kiss","a trip you'd take with me","the way you say goodnight to me","your favorite photo of us","the moment you felt close to me","your love language","the most romantic movie scene","a love letter you'd write me","your favorite thing about my smile","the little habits of mine that you love","the meal you'd cook for me","a slow dance with me","your perfect Sunday with me","the pet name you'd give me","the first gift you'd give me","a sunset with me","our future home","a rainy day with me","the best hug we ever had","the way I say your name","what you'd pack for a getaway with me","the day you knew you liked me"],
"fun":["your weirdest talent","your worst haircut","your most embarrassing moment","your guilty-pleasure song","your dream superpower","the funniest dream you remember","your worst cooking disaster","your most useless skill","your silliest fear","the last thing that made you laugh out loud","your most awkward date","your childhood nickname","your hidden obsession","the worst gift you ever received","your karaoke song","your most embarrassing school memory","a snack you can't live without","your most dramatic moment","the silliest fight you've ever had","your worst fashion choice","the animal you'd be","your secret dance moves","the strangest thing in your fridge","your go-to excuse for being late","a rule you'd invent for the world","the most spontaneous thing you've done","your lucky charm","your alter-ego name","the last thing you googled","your most chaotic road trip"],
"met":["your first thought when we first texted","what you do on a lazy Saturday","your favorite place in your city","your dream job as a kid","the last show you binged","your comfort food","your morning routine","a place you'd love to travel to","your favorite childhood memory","the best advice you ever got","your biggest hobby","your most used app","a talent people don't expect from you","your favorite season","a book or movie that changed you","your biggest pet peeve","your ideal weekend","the song you play the most","what you were like in school","the best meal you ever had","your family traditions","your bucket list","your funniest travel story","your dream house","the person you admire most","a small thing that makes your day","what you value in a friend","your favorite way to spend a rainy day","your biggest goal this year","your best-kept talent"],
"lovers":["the first time you said 'I love you'","our favorite inside joke","the way I hold your hand","a morning waking up next to me","your favorite thing about our relationship","a cozy night in with me","the best surprise I ever gave you","how I make you feel safe","our best anniversary","the little things I do that melt you",
"a kiss you still think about","the way I look at you","the outfit of mine you love most","what you miss most when I'm away","a late-night conversation we had","the moment you couldn't stop smiling at me","a dance under the stars with me","what you'd whisper in my ear","our most romantic night","the first time you felt butterflies with me",
"what attracts you most about me","what makes your heart race when I'm close","a slow kiss on a balcony","the flirtiest thing you'd say to me tonight","what you find irresistible about me","a private date night we'd plan","the way I say your name when I'm teasing you","your favorite way to be close to me","the compliment that would make me blush","what you'd whisper to me across a crowded room"],
"friends":["the funniest thing we did together","our craziest adventure","the day we became friends","your favorite memory of our group","the time I helped you most","an inside joke only we understand","a secret you kept for me","the worst advice I ever gave you","our most embarrassing moment together","a trip we should take","the best road-trip song","the movie night we'll never forget","the time we laughed until we cried","what you admire about me","a nickname you'd give me","the silliest argument we had","what you'd put in a time capsule for us","the moment you knew we'd be friends for life","a dare you'd never let me forget","the best meal we shared","your favorite photo of us two","the time I embarrassed you","what you'd say in a toast at my birthday","our theme song","the weirdest thing we have in common","the party we'll never forget","a goal we should chase together","my most annoying habit","what you'd do if we swapped lives for a day","the best thing about being my friend"]}
from ar import AR_TF,AR_DF,AR_TOP
build=lambda fr,tp:[f.replace("{t}",t) for t in tp for f in fr]
def gen(TF,DF,TOP):
    assert all(len(v)==30 for v in TOP.values()) and len({t for v in TOP.values() for t in v})==150
    out={"truth":{},"dare":{}}
    for kind,fr in(("truth",TF),("dare",DF)):
        for lv,tp in TOP.items():
            if lv=="lovers":
                for i in range(3):out[kind]["lovers%d"%i]=build(fr,tp[i*10:i*10+10])
            else:out[kind][lv]=build(fr,tp)
        a=[x for v in out[kind].values() for x in v];assert len(a)==3000==len(set(a)),kind
    return out
import pairs
E=gen(TF,DF,TOP);E["ch"]=pairs.EN
A=gen(AR_TF,AR_DF,AR_TOP);A["ch"]=pairs.AR
json.dump({"en":E,"ar":A},open("public/data.json","w"),ensure_ascii=False,separators=(",",":"))
print("ok: 3000 truths + 3000 dares in English and in Arabic")
