# Premade options for "If you had to choose": the game picks two different options from the level's list.
EN={
"romantic":["a candlelit dinner at home","a picnic under the stars","a surprise weekend trip","a handwritten love letter","dancing in the kitchen at midnight","a quiet night watching movies","a sunset walk on the beach","cooking a meal together","a long road trip with our playlist","a spontaneous kiss in the rain","breakfast in bed every Sunday","a cabin by the lake","stargazing from a rooftop","a slow dance in the living room","a day exploring a new city together","a surprise romantic message every morning","a couples' massage","a hot-air balloon ride","a cozy winter evening by the fireplace","a trip to the city of love"],
"fun":["being able to fly","reading minds","a month with no phone","eating pizza every day","living in a treehouse","having a pet dragon","never needing sleep","talking to animals","being famous for a day","time-traveling to the past","time-traveling to the future","a rewind button for your life","dancing every time you hear music","owning a candy shop","swapping lives with a celebrity","being invisible whenever you want","a talking parrot as a roommate","teleporting anywhere","living inside a movie","a robot butler"],
"met":["a quiet weekend at home","an adventurous trip abroad","a big party","a small dinner with close friends","a morning run","a lazy morning in bed","watching a series","reading a book","a beach holiday","a mountain hike","a road trip","a city break","cooking at home","dining out","a museum visit","a live concert","a board-game night","a movie night","a picnic in the park","a spontaneous plan"],
"lovers0":["a cozy night in","holding hands on a long walk","a love song dedicated to me","cooking together","a movie night under one blanket","a handwritten note every day","breakfast together","a gentle morning cuddle"],
"lovers1":["a slow dance at home","a surprise date night","a long kiss at sunset","a weekend away just us","whispering sweet words at night","a romantic bath with candles","a playful pillow fight","a secret rendezvous"],
"lovers2":["a flirty massage","a midnight kiss on the balcony","a teasing game of truth or dare","a private dance just for me","a long, slow kiss","a champagne night just us","a mischievous text all day","a candlelit dinner with a surprise for dessert"],
"friends":["a road trip with friends","a game night","a camping trip","a beach day","a late-night talk","a surprise party","a cooking challenge","a karaoke night","a hiking adventure","a movie marathon","a shopping spree together","a festival weekend","a picnic","a bowling night","a trip abroad together","a day at an amusement park","a sleepover","a study session together","a concert","an escape room"]}
AR={
"romantic":["عشاء على ضوء الشموع في البيت","نزهة تحت النجوم","رحلة نهاية أسبوع مفاجئة","رسالة حب مكتوبة بخط اليد","الرقص في المطبخ عند منتصف الليل","ليلة هادئة لمشاهدة الأفلام","مشي عند الغروب على الشاطئ","إعداد وجبة معًا","رحلة طويلة بالسيارة مع أغانينا","قبلة عفوية تحت المطر","فطور في السرير كل أحد","كوخ على ضفة بحيرة","مراقبة النجوم من سطح المبنى","رقصة هادئة في غرفة المعيشة","يوم لاستكشاف مدينة جديدة معًا","رسالة رومانسية مفاجئة كل صباح","جلسة تدليك للثنائي","رحلة في منطاد","أمسية شتوية دافئة قرب المدفأة","رحلة إلى مدينة الحب"],
"fun":["القدرة على الطيران","قراءة الأفكار","شهر كامل بلا هاتف","أكل البيتزا كل يوم","العيش في بيت على شجرة","امتلاك تنين أليف","عدم الحاجة إلى النوم أبدًا","التحدث مع الحيوانات","الشهرة ليوم واحد","السفر عبر الزمن إلى الماضي","السفر عبر الزمن إلى المستقبل","زر للعودة بالزمن في حياتك","الرقص كلما سُمعت موسيقى","امتلاك محل حلويات","تبديل الحياة مع شخص مشهور","الاختفاء متى شئت","ببغاء يتكلم يشاركك السكن","الانتقال الفوري إلى أي مكان","العيش داخل فيلم","خادم آلي في البيت"],
"met":["عطلة هادئة في البيت","رحلة مغامرات إلى الخارج","حفلة كبيرة","عشاء صغير مع المقربين","جري صباحي","صباح كسول في السرير","متابعة مسلسل","قراءة كتاب","عطلة على الشاطئ","رحلة تسلق جبلية","رحلة بالسيارة","جولة قصيرة في مدينة","الطبخ في البيت","الأكل في مطعم","زيارة متحف","حضور حفل موسيقي","ليلة ألعاب لوحية","ليلة أفلام","نزهة في الحديقة","خطة عفوية"],
"lovers0":["ليلة دافئة في البيت","الإمساك باليد في نزهة طويلة","أغنية حب مهداة إليّ","الطبخ معًا","ليلة أفلام تحت بطانية واحدة","ورقة حب كل يوم","فطور معًا","عناق صباحي هادئ"],
"lovers1":["رقصة بطيئة في البيت","موعد مفاجئ في المساء","قبلة طويلة عند الغروب","عطلة نهاية أسبوع لنا وحدنا","همس كلمات حلوة في الليل","حمّام رومانسي بالشموع","معركة وسائد مرحة","لقاء سري"],
"lovers2":["تدليك مغازل","قبلة منتصف الليل على الشرفة","لعبة مشاكسة لصراحة أم تحدٍّ","رقصة خاصة لي وحدي","قبلة طويلة وبطيئة","أمسية شمبانيا لنا وحدنا","رسالة مشاكسة طوال اليوم","عشاء على ضوء الشموع وبعده مفاجأة"],
"friends":["رحلة بالسيارة مع الأصدقاء","ليلة ألعاب","رحلة تخييم","يوم على الشاطئ","حديث طويل في آخر الليل","حفلة مفاجأة","تحدي طبخ","ليلة كاريوكي","مغامرة تسلق","ماراثون أفلام","جولة تسوق معًا","عطلة نهاية أسبوع في مهرجان","نزهة","ليلة بولينغ","رحلة إلى الخارج معًا","يوم في مدينة الألعاب","ليلة مبيت عند صديق","جلسة مذاكرة معًا","حضور حفل موسيقي","غرفة هروب"]}
for P in(EN,AR):
    assert set(P)==set(EN) and all(len(set(v))==len(v) for v in P.values())
    assert all(len(P[k])==(8 if k.startswith("lovers") else 20) for k in P)
